version: "3"
services:
  login-container:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=Sandy-dev
      - CHOKIDAR_USEPOLLING=true